### ISSUE TITLE
[Security] Invalidate all sessions on password change  

### ISSUE THREAD

**Issue by Omranic** [rinvex/laravel-auth#139]

**Comment by noxify** [comment]
Just an idea how to solve this:

Currently we have the following implementation in the Controller:
https://github.com/rinvex/fort/blob/develop/resources/stubs/controllers/Memberarea/AccountSessionsController.stub#L33-L39

The easiest way is to duplicate the following line

```
app('rinvex.fort.session')->where('user_id', $request->user($this->getGuard())->id)->delete();
```

My idea was to extract the session termination into an event.
If the password was changed successfully, we're executing command, which terminates the sessions then.

I think with this, we have more flexibility and we can reuse it (e.g. after changing the email/username)

**Comment by Omranic** [comment]
To be revised & implemented soon god willing!

**Comment by Omranic** [comment]
This is no longer needed as this feature is handled automatically now through `Cortex\Auth\Http\Middleware\AuthenticateSession` middleware!
