### ISSUE TITLE
[Feature] Impersonate other accounts for admins

### ISSUE THREAD

**Issue by Omranic** [rinvex/laravel-auth#142]

**Comment by noxify** [comment]
What do you think about https://github.com/404labfr/laravel-impersonate ?

Found via: https://murze.be/2017/02/laravel-package-impersonate-users/

**Comment by Omranic** [comment]
Looks nice, but needs integration into our permissions system so we can assign who can impersonate & so on, not like the default `README` says through method override. We can use it as a base, and build upon it..

**Comment by Omranic** [comment]
To be revised! It's highly recommended to use existing package instead of implementing our own -new wheel-!

**Comment by Omranic** [comment]
Not a priority, plus third-party package could be used, no need to be re-implemented!
